// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	domains "github.com/msGo22/lesson5/internal/core/domains"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// MockTeacherRepo is an autogenerated mock type for the TeacherRepo type
type MockTeacherRepo struct {
	mock.Mock
}

// Araba provides a mock function with given fields:
func (_m *MockTeacherRepo) Araba() {
	_m.Called()
}

// GetByID provides a mock function with given fields: ID
func (_m *MockTeacherRepo) GetByID(ID uint) (*domains.Teacher, error) {
	ret := _m.Called(ID)

	var r0 *domains.Teacher
	if rf, ok := ret.Get(0).(func(uint) *domains.Teacher); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domains.Teacher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: teacher
func (_m *MockTeacherRepo) Save(teacher *domains.Teacher) error {
	ret := _m.Called(teacher)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domains.Teacher) error); ok {
		r0 = rf(teacher)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockTeacherRepo creates a new instance of MockTeacherRepo. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTeacherRepo(t testing.TB) *MockTeacherRepo {
	mock := &MockTeacherRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
